<?
$PERM["wood"]["2"]="D";
$PERM["wood"]["5"]="D";
$PERM["wood"]["3"]="D";
$PERM["wood"]["4"]="D";
$PERM["wood"]["6"]="D";
$PERM["wood"]["7"]="D";
$PERM["wood"]["*"]="D";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>